apiVersion: apps/v1
kind: Deployment
metadata:
  name: container
  namespace: default
spec:
  selector:
    matchLabels:
      app: container
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
        - name: ubuntu
          image: mcr.microsoft.com/oss/kubernetes/pause:3.6
          imagePullPolicy: Always
          securityContext:
            privileged: true
